### ISSUE TITLE
checklist for 2021.06 pilot

### ISSUE THREAD

**Issue by boegel** [EESSI/compatibility-layer#101]
* [x] define 2021.06 set (PRs: https://github.com/EESSI/gentoo-overlay/pull/40 + https://github.com/EESSI/gentoo-overlay/pull/41)
* [x] update Prefix bootstrap snapshot + script (PR: https://github.com/EESSI/compatibility-layer/pull/109)
* [x] use new build container (PR: #98)
* [x] switch to `git` rather than `rsync` for `emerge --sync` (issue: #100, PR: https://github.com/EESSI/compatibility-layer/pull/106)
* [x] fix timezone issue (#93)
* [x] tweak trusted glibc dirs (cfr. https://github.com/EESSI/software-layer/issues/108)
* [x] add test step to playbook (PR: https://github.com/EESSI/compatibility-layer/pull/108)
* [x] generate env file for glibc (issue: #104, PR: https://github.com/EESSI/compatibility-layer/pull/107)
* build compat layer for:
    * [x] `aarch64`
    * [x] `ppc64le`
    * [x] `x86_64`
* [x] update CI (`.github/workflows/pilot_repo.yml `)

**Comment by ocaisa** [comment]
Can we consider https://github.com/EESSI/software-layer/issues/108 for inclusion here. The repercussions for the compatibility layer would be a change in the trusted glibc dirs (to, for example, `/cvmfs/pilot.eessi-hpc.org/host_injections/2021.03/compat/linux/x86_64/lib` where `/cvmfs/pilot.eessi-hpc.org/host_injections` is a variable symlink in CVMFS).

**Comment by boegel** [comment]
I think it's worth looking into that, yes, added it to the list.
@bedroge Is this something you can look into?

**Comment by bedroge** [comment]
@boegel Sure, I'll try to take a look at it.

@ocaisa just to make sure that I get it: the only required change in the Ansible playbook that installs the compatibility layer is that it should use `user-defined-trusted-dirs=/cvmfs/pilot.eessi-hpc.org/host_injections` (instead of the old one `/opt/eessi/lib`)? And then the repo should get a variant symlink that will point that dir by default to `/opt/eessi`, but can be overridden using something like `$EESSI_HOST_INJECTIONS_PATH`?

**Comment by ocaisa** [comment]
@bedroge Not quite. The trusted dir would be a moving target depending on the pilot release (plus system characteristics), so
```
user-defined-trusted-dirs=/cvmfs/pilot.eessi-hpc.org/host_injections/$EESSI_PILOT_VERSION/compat/$EESSI_OS_TYPE/$EESSI_CPU_FAMILY/lib
```

The idea is that the CVMFS variant symlink is for `/cvmfs/pilot.eessi-hpc.org/host_injections` and that we would then have a tool that would correctly populate (and test) the trusted dir. This would allow us to catch, for example, whether CUDA drivers are new enough for our shipped CUDA stack.

**Comment by bedroge** [comment]
I do see what you're after, but I'm not sure If I get the details / if that's possible. Why do we need the variant symlink for `/cvmfs/pilot.eessi-hpc.org/host_injections`, and how does that have subdirs if it's a (variant) symlink? Shouldn't the whole thing `/cvmfs/pilot.eessi-hpc.org/host_injections/$EESSI_PILOT_VERSION/compat/$EESSI_OS_TYPE/$EESSI_CPU_FAMILY/lib` be a (variant) symlink that a user/admin can override to a local directory?

**Comment by ocaisa** [comment]
The subdirectory structure `$EESSI_PILOT_VERSION/compat/$EESSI_OS_TYPE/$EESSI_CPU_FAMILY/lib` is created by the script on the host system in a directory that is controlled by whomever controls the CVMFS config. The variant symlink just points to the dir that will contain that structure.

**Comment by bedroge** [comment]
I get it now, brilliant idea! :-)
